[package]
name = "wasm-multi-memory-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = "2.0.67"
wasm-multi-memory-polyfill = { version = "0.1.0", path = "../wasm-multi-memory-polyfill" }

[lib]
proc-macro = true
