[package]
name = "tcore"
version = "0.4.0"
edition = "2021"
license = "CC0-1.0"
description = "Performs tail call optimization on a WAFFLE module"

[dependencies]
anyhow = "1.0.86"

portal-pc-waffle.workspace = true
stacker = "0.1.17"
waffle-ast = { version = "0.4.0", path = "../waffle-ast" }
