[package]
name = "waffle-trie"
version = "0.4.3"
edition = "2021"
license = "CC0-1.0"
description = "Trie mapping for waffle"

[dependencies]
anyhow = "1.0.86"
portal-pc-waffle.workspace = true
trie-rs = "0.4.2"
waffle-ast = { version = "0.4.0", path = "../waffle-ast" }
